create table if not exists public.waitlist_subscribers (
  id bigint generated by default as identity primary key,
  full_name text not null check (char_length(trim(full_name)) >= 2),
  email text not null check (email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'),
  phone text not null check (char_length(trim(phone)) >= 6),
  university text,
  year_semester text,
  interest_areas text[] not null default '{}'::text[],
  source text not null default 'agendier-launch-site',
  created_at timestamptz not null default now()
);

create unique index if not exists waitlist_subscribers_email_unique
  on public.waitlist_subscribers (lower(email));

alter table public.waitlist_subscribers enable row level security;

grant insert on public.waitlist_subscribers to anon, authenticated;

drop policy if exists "Allow public waitlist inserts" on public.waitlist_subscribers;

create policy "Allow public waitlist inserts"
  on public.waitlist_subscribers
  for insert
  to anon, authenticated
  with check (true);

comment on table public.waitlist_subscribers is
  'Private Agendier launch site waitlist submissions inserted by the Vercel API function.';
